### ISSUE TITLE
当表单通过 iframe 的方式嵌入到第三方网站时，不能在 Safari 和 Firefox 下工作

### ISSUE THREAD

**Issue by wongyouth** [huacnlee/rucaptcha#107]
Safari 和 Firefox 默认情况下不支持第三方的 cookies。能否升级为不使用 cookies，改成表单内嵌入一个隐藏的字段含有原先的 session id 值去做比较。

**Comment by wongyouth** [comment]
For anyone encountering the same issue, I created a gem at https://github.com/wongyouth/rucaptcha_no_cookies as a temporary fix.

**Comment by wongyouth** [comment]
The timeline of third-party cookie deprecation of Chrome.
https://developers.google.com/privacy-sandbox/3pcd

**Comment by huacnlee** [comment]
Going to close, this is not issue of RuCaptcha, it a iframe special limit.
