### ISSUE TITLE
windows10 如何安装3.2版本，目前只能安装2.6

### ISSUE THREAD

**Issue by kuangviyu** [huacnlee/rucaptcha#108]
windows10 下安装3.2版本提示错误如下：
`Building native extensions. This could take a while...
ERROR:  Error installing rucaptcha:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rucaptcha-3.2.3/ext/rucaptcha
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 extconf.rb
checking for gcc... yes
checking for g++... yes
checking for x86_64-w64-mingw32-gcc-ar... yes
checking for cargo... no

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rucaptcha-3.2.3/ext/rucaptcha
make DESTDIR\= sitearchdir\=./.gem.20240314-1204-tzdbqp sitelibdir\=./.gem.20240314-1204-tzdbqp clean

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rucaptcha-3.2.3/ext/rucaptcha
make DESTDIR\= sitearchdir\=./.gem.20240314-1204-tzdbqp sitelibdir\=./.gem.20240314-1204-tzdbqp
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
make: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rucaptcha-3.2.3/ext/rucaptcha/.rb-sys/stable/cargo/bin/rustup: No such file or directory
make: *** [Makefile:541：C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rucaptcha-3.2.3/ext/rucaptcha/.rb-sys/stable/cargo/bin/cargo] 错误 127

make failed, exit code 2`

**Comment by huacnlee** [comment]
你这个错误是 Rust 没安装，Windows 没有预编译的版本，所以安装的时候需要 Rust

**Comment by kuangviyu** [comment]
> 你这个错误是 Rust 没安装，Windows 没有预编译的版本，所以安装的时候需要 Rust
> 
> 另外，这个库没做 Windows 支持，所以不保证能运行，你可以试试看有可能可以。

收到，非常感谢！
