### ISSUE TITLE
The picture not shown completely

### ISSUE THREAD

**Issue by jstdoit** [huacnlee/rucaptcha#16]
as mentioned in title, my verify code picture cannot show completely, as link followed:

http://standard.cfda.pub:8800/rucaptcha

my os system is centos 6.5, and rails version is: 4.2.4

**Comment by huacnlee** [comment]
Put your configs here

**Comment by jstdoit** [comment]
RuCaptcha.configure do
  # Number of chars, default: 4
  self.len = 4 
  # Image font size, default: 45
  self.font_size = 45
  # Cache generated images in file store, this is config files limit, default: 100
  # set 0 to disable file cache.
  self.cache_limit = 100 
end

**Comment by huacnlee** [comment]
try version 0.3.2

**Comment by jstdoit** [comment]
it works, thanks.
