### ISSUE TITLE
Readme 加上 centos 安装的支持

### ISSUE THREAD

**Issue by xiajian** [huacnlee/rucaptcha#19]
请在 readme 中的 required 中 上添加： 

## Centos

```
sudo yum install -y ImageMagick ImageMagick-devel ghostscript
```

**Comment by qx** [comment]
貌似没用,我装上还是报错

> App 14462 stderr: RuntimeError (RuCaptcha: convert: delegate library support not built-in '/usr/share/fonts/default/Type1/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1740.
> App 14462 stderr: convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/508.
> App 14462 stderr: convert: delegate library support not built-in '/usr/share/fonts/default/Type1/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1740.
> App 14462 stderr: convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/508.
> App 14462 stderr: convert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3235.):
> App 14462 stderr:   rucaptcha (0.5.0) lib/rucaptcha/captcha.rb:81:in `create'
> App 14462 st
