### ISSUE TITLE
verify_rucaptcha?

### ISSUE THREAD

**Issue by caiqinghua** [huacnlee/rucaptcha#28]
在本地调试，单步跟踪，发现 verify_rucaptcha?(@user) 一直返回false，请问可能是什么原因？

**Comment by huacnlee** [comment]
我不知道你怎么用的，得讲清楚每一个细节

**Comment by caiqinghua** [comment]
谢谢华顺，已经知道原因了，是因为时间过期，过期时间默认为120s有点短，我要自己配置为长一点时间，长一点时间没有啥风险吧？想配置为5分钟。另外能不能点击刷新验证码？

**Comment by caiqinghua** [comment]
其实是我的使用场景有问题，120s应该足够了，我应该先用js进行图片验证码验证，再进行短信验证码验证
