### ISSUE TITLE
convert: unable to read font

### ISSUE THREAD

**Issue by TangMonk** [huacnlee/rucaptcha#32]
在Docker上部署，使用Rails:4.2.4 Image，出现如下错误：

```
I, [2016-09-25T07:50:07.888809 #1]  INFO -- : Processing by RuCaptcha::CaptchaController#index as HTML
E, [2016-09-25T07:50:07.943286 #1] ERROR -- :   RuCaptcha   RuCaptcha convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1127.
convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1127.
convert: no images defined `png:-' @ error/convert.c/ConvertImageCommand/3210.
```

**Comment by huacnlee** [comment]
Try this solutions

http://stackoverflow.com/questions/1014506/imagemagickerror-unable-to-read-font-null-null
http://stackoverflow.com/questions/13936256/imagemagick-error-while-running-convert-convert-unable-to-read-font

**Comment by TangMonk** [comment]
@huacnlee thanks,  run `apt-get install ghostscript` on debain works
