### ISSUE TITLE
verify_rucaptcha? false

### ISSUE THREAD

**Issue by Janady** [huacnlee/rucaptcha#33]
生成验证码的图片正常，verify_rucaptcha?(@user) 返回false，且@user上并没有:base的error

**Comment by huacnlee** [comment]
不知道你在说什么问题

**Comment by Janady** [comment]
原因是store_info = Rails.cache.read(rucaptcha_sesion_key_key)总是返回nil，
改成session[:_rucaptcha]来缓存就没有问题！

不知道我配置了哪里导致cache失效，但write之后马上read能读出写入的hash。

**Comment by Janady** [comment]
我需要在开发环境中设置允许cache，问题解决了

**Comment by huacnlee** [comment]
看起来还需要调整一下，避免再次遇坑

**Comment by huacnlee** [comment]
https://github.com/huacnlee/rucaptcha/commit/771a5621ff972c5ca7d8b4b9cc1dff50079d60ba

恢复到 Session 存储验证码，改为给出 warning
