### ISSUE TITLE
应用使用https的时候生成的链接还是http

### ISSUE THREAD

**Issue by firebroo** [huacnlee/rucaptcha#34]
生成的代码
<src="http://xxx.com">
产生警告
was loaded over HTTPS, but requested an insecure image 'http://www.xxx.com/rucaptcha/'. This content should also be served over HTTPS.

**Comment by huacnlee** [comment]
https://ruby-china.org/account/password/new

没有这样的问题呀？

**Comment by huacnlee** [comment]
用 1.1.2 避免生成带 host 的地址，这样就不会有问题了
