### ISSUE TITLE
如果配置文件设置为redis_store, 但并不启动redis， 验证码能出来，但无法验证通过。

### ISSUE THREAD

**Issue by netqyq** [huacnlee/rucaptcha#44]
如果配置文件设置为redis_store, 但并不启动redis， 验证码能出来，但一直无法验证通过。
这可能是个小问题。

理想的方式是：
配置文件设置为redis_store, 但连接不到redis，就使用file_store.

**Comment by liuzhenangel** [comment]
我用的redis_store，加了个gem 'redis-rails', 不用启动redis使用正常。

如果不加这个 gem redis-rails 就不显示图片。
