### ISSUE TITLE
Invalid message not shown

### ISSUE THREAD

**Issue by leiz-me** [huacnlee/rucaptcha#46]
I am using this gem without devise, version == 2.1.3.

Not sure why but cannot get the invalid message. Just follow the instructions.
Now in order to get an error message, I have to manually add a line of code to make it happen.

```ruby
    if verify_rucaptcha?(@user) && @user.save
      @user.send_activation_email
      redirect_to activate_user_url(@user)
    else
      # this one below
      @user.errors.add(:base, t('rucaptcha.invalid'))
      render :new
    end
````

**Comment by huacnlee** [comment]
Send a PR for update README

**Comment by leiz-me** [comment]
README updated
