### ISSUE TITLE
2.3.1 的 ruby 好像不能加载，2.3.0的可以

### ISSUE THREAD

**Issue by nicozhang** [huacnlee/rucaptcha#51]
原本我是想在console 里直接 require，但发现执行不了，总是找不到文件。换到2.3.0，就可以了，是版本的问题吗？

**Comment by huacnlee** [comment]
升级了 Ruby 这个库是应该是需要重新安装的

**Comment by huacnlee** [comment]
Ruby 2.3.1 能跑，Ruby China 试过的
