### ISSUE TITLE
生成的图片只能是200*70的吗？怎么设置图片大小？

### ISSUE THREAD

**Issue by yjw2015** [huacnlee/rucaptcha#53]

**Comment by yjw2015** [comment]
rucaptcha.c 这个文件怎么修改图片为100*40？

**Comment by jicheng1014** [comment]
我觉得改c 那块代码太麻烦了   直接改css 吧

**Comment by huacnlee** [comment]
无法改变尺寸

**Comment by tagliala** [comment]
I'm facing the same issue.

If it could help, I'm using `image-rendering: pixelated;` to keep the captcha at the original size of 200x70 and crisper on HDPI displays.

![image](https://user-images.githubusercontent.com/556268/50042562-e037e580-0064-11e9-96ab-2d8fd9aaf19e.png)

Ref: https://css-tricks.com/almanac/properties/i/image-rendering/

Browser support: https://caniuse.com/css-crisp-edges

**Comment by Nimazhabu** [comment]
怎么重置验证图片

**Comment by huacnlee** [comment]
@Nimazhabu 最新版本已经实现了刷新功能（内置的）
