### ISSUE TITLE
我在这个gem的基础上做了修改，需要合入吗

### ISSUE THREAD

**Issue by liuzhenangel** [huacnlee/rucaptcha#56]
我引入这个gem后，用的人都反馈验证码看不太清，每次要输入四五次才能成功，所以我把这个验证码改成了 4 位，没有横线，看起来清晰很多。
![image](https://user-images.githubusercontent.com/7440044/33587899-2f3e7950-d9ab-11e7-8f08-3d6e8d324893.png)
我想合到你这边，不知道需不需要？

**Comment by huacnlee** [comment]
删除线不能去掉，是为了混淆用的，4位长度倒是可以接受
