### ISSUE TITLE
a-y-do-not-match-captcha-failed

### ISSUE THREAD

**Issue by wpzero** [huacnlee/rucaptcha#67]
"abcdafahijklmnopqrstuvwxyz"
"abcdyfhhijklmnopqrstuvwxyz"

https://github.com/ITikhonov/captcha

https://github.com/huacnlee/rucaptcha/blob/master/ext/rucaptcha/rucaptcha.c#L154

**Comment by goofansu** [comment]
Bring in https://github.com/huacnlee/rucaptcha/commit/682aa39ec0330c0aa2707a351bad8fc25356c9a0#diff-042bdabad0dbc24599fe594b71734b75R154
