### ISSUE TITLE
2.4.0 把 2.0.1 中 CDN 的 fix 又改回去了？

### ISSUE THREAD

**Issue by huobazi** [huacnlee/rucaptcha#73]
如题

https://github.com/huacnlee/rucaptcha/commit/1d1742e2ed53afc52caa63486a2c08e1826224d3#diff-6907c77bc234a277c33a94de5b2449ed

https://github.com/huacnlee/rucaptcha/commit/771b7afaa00efb62a16693403f3314ae1c0429e2#diff-6907c77bc234a277c33a94de5b2449ed

**Comment by huacnlee** [comment]
😂 需要在哪里加个注释说明

**Comment by huacnlee** [comment]
@huobazi https://github.com/huacnlee/rucaptcha/pull/58 修改的原因是这个

**Comment by huobazi** [comment]
@huacnlee 
这样的话，如果设置了 ```config.action_controller.asset_host``` 会导致产生的图片带上 cdn 的 host
类似如下这两个问题：
https://github.com/ruby-china/homeland/pull/856
https://github.com/huacnlee/rucaptcha/pull/39

目前，估计由于
ruby-china 的代码中的 rucaptcha 是2.3.1
https://github.com/ruby-china/homeland/blob/master/Gemfile.lock#L403
所以这个问题没有暴露出来
