### ISSUE TITLE
希望可提供 redis_store 的配置功能

### ISSUE THREAD

**Issue by jstdoit** [huacnlee/rucaptcha#75]
如果配置了:redis_store，则会通过lookup_store获取一个cache的obj，但获取到的redis_store是默认配置，通常是指向127.0.0.1的，但如果这个redis_store不在::1上呢？

**Comment by huacnlee** [comment]
这项配置默认基于 Rails cache store 的配置，你只需要修改 Rails cache_store 的配置为 Redis 即可。。当然，你也可以用类似 cache_store 的参数来配置 RuCaptcha

**Comment by jstdoit** [comment]
好的，怪我文档没有读透，谢谢
