### ISSUE TITLE
集成到homeland的发帖中输入失败没有提示，输入失败后再输入正确的验证码不通过

### ISSUE THREAD

**Issue by bestjane** [huacnlee/rucaptcha#91]
![image](https://user-images.githubusercontent.com/8843246/87954201-9b94eb80-cade-11ea-81a7-5e575a096b1e.png)
![image](https://user-images.githubusercontent.com/8843246/87954260-ae0f2500-cade-11ea-93ba-d55534a03f7a.png)
1. 输入失败没有提示
2. 输入失败后再输入正确的验证码不通过
@huacnlee

**Comment by huacnlee** [comment]
https://github.com/huacnlee/rucaptcha/pull/98

Fixed this issue
